version: '3.0'

networks:
  dh:
    external: true
    
services:
  postgres:
    networks:
      - dh
    image: postgres:16
    container_name: dh
    environment:
      POSTGRES_DB: "dh"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql