version: '3.0'

networks:
  dh:
    external: true

services:
  producer:
    image: osipovmr/dh-kafka-producer:latest
    container_name: kafka-producer
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: 8081
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      TOPIC: 'event'
      PARTITIONS: 1
      # At most once  0
      # Продюсер не ждёт подтверждения от брокера Kafka.
      # Сообщение считается отправленным сразу после попытки отправки.
      # At least once -1 all
      # Эта семантика гарантирует, что сообщение будет обработано хотя бы один раз.
      # Если происходит сбой, сообщение может быть дублировано. Продюсер ждёт подтверждения от всех реплик брокера Kafka.
      # Exactly once
      # Эта семантика гарантирует, что сообщение будет обработано строго один раз
      # enable.idempotence=true:
      # -1 all
      ACKS: '0'
    networks:
      - dh

  consumer:
    image: osipovmr/dh-kafka-consumer:latest
    container_name: kafka-consumer
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      SPRING_KAFKA_CONSUMER_GROUP_ID: 'ift'
      TOPIC: 'event'
    networks:
      - dh
    depends_on:
      - kafka
      - producer
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKA_ALLOW_AUTO_CREATE_TOPICS: 'true'
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092, CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: dh-cluster
      KAFKA_CREATE_TOPICS: '__consumer_offsets'
    depends_on:
      - producer
    networks:
      - dh

  ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: dh-osipov
    depends_on:
      - kafka
    networks:
      - dh