server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dh
    username: admin
    password: password
logging:
  level:
    kafka: off
properties:
  classpath: "classpath:"
